RELATIVES_CREATURE_MOVES_PER_STEP = 3
DEGREES_CREATURE_ROTATES_PER_STEP = 10

MAX_LIFESPAN = 400
MAX_SENSOR_LENGTH = 30

FOOD_ADDED_PER_STEP = 0.01
FOOD_LOST_ON_STEP = 0.03
MAX_FOOD_DIFFERNCE_FOR_NO_LOSS = 0.15
MAX_FOOD_LOSS = 2
STARTING_SIZE = 3

MIN_WEIGHT_MUTATION = -0.05
MAX_WEIGHT_MUTATION = 0.05

MIN_COLOR_CHANGE = -0.05
MAX_COLOR_CHANGE = 0.05

MIN_SENSOR_LEN_MUTATION = -5
MAX_SENSOR_LEN_MUTATION = 5

MIN_SENSOR_ANGLE_MUTATION = -10
MAX_SENSOR_ANGLE_MUTATION = 10

N_POPULATION = 300
MAX_POPULATION = 3000

MAX_CREATURE_SIZE = 10
FOOD_LOST_ON_NEW_CHILD = 11
STARTING_FOOD = 8
FOOD_LOST_ON_WATER = 1
EVO_STEPS_PER_FRAME = 4