RELATIVES_CREATURE_MOVES_PER_STEP = 3
DEGREES_CREATURE_ROTATES_PER_STEP = 10

MAX_LIFESPAN = 108000
MAX_SENSOR_LENGTH = 30

FOOD_ADDED_PER_STEP = 2
FOOD_LOST_ON_STEP = 2
MAX_FOOD_DIFFERNCE_FOR_NO_LOSS = 40
MAX_FOOD_LOSS = 10
STARTING_SIZE = 8

MIN_WEIGHT_MUTATION = -0.0005
MAX_WEIGHT_MUTATION = 0.0005

MIN_COLOR_CHANGE = -5
MAX_COLOR_CHANGE = 5

MIN_SENSOR_LEN_MUTATION = -5
MAX_SENSOR_LEN_MUTATION = 5

MIN_SENSOR_ANGLE_MUTATION = -10
MAX_SENSOR_ANGLE_MUTATION = 10

N_POPULATION = 1
MAX_POPULATION = 20